export const SERVICE_STAGES = {
  "Projeto Topográfico Planimétrico": [
    "Contato com o cliente",
    "Envio de proposta comercial",
    "Envio de contrato",
    "Contrato assinado",
    "Marcar levantamento técnico",
    "Levantamento técnico",
    "Processamento de dados",
    "Elaboração de projeto técnico",
    "Elaboração de memorial descritivo",
    "Correção cruzada",
    "Emissão de ART",
    "Impressão de projeto",
    "Entrega ao cliente",
    "Coleta de NPS",
  ],
  "Projeto Topográfico Planialtimétrico": [
    "Contato com o cliente",
    "Envio de proposta comercial",
    "Envio de contrato",
    "Contrato assinado",
    "Marcar levantamento técnico",
    "Levantamento técnico",
    "Processamento de dados",
    "Elaboração de projeto técnico",
    "Elaboração de memorial descritivo",
    "Correção cruzada",
    "Emissão de ART",
    "Impressão de projeto",
    "Entrega ao cliente",
    "Coleta de NPS",
  ],
  Usucapião: [
    "Contato com o cliente",
    "Envio de proposta comercial",
    "Envio de contrato",
    "Contrato assinado",
    "Marcar levantamento técnico",
    "Levantamento técnico",
    "Processamento de dados",
    "Elaboração de projeto técnico",
    "Elaboração de memorial descritivo",
    "Correção cruzada",
    "Emissão de ART",
    "Impressão de projeto",
    "Entrega ao cliente",
    "Coleta de NPS",
  ],
  "Fusão/Desmembramento": [
    "Contato com o cliente",
    "Envio de proposta comercial",
    "Envio de contrato",
    "Contrato assinado",
    "Marcar levantamento técnico",
    "Levantamento técnico",
    "Processamento de dados",
    "Elaboração de projeto técnico",
    "Elaboração de memorial descritivo",
    "Correção cruzada",
    "Emissão de ART",
    "Impressão de projeto",
    "Entrega ao cliente",
    "Coleta de NPS",
  ],
  "Georreferenciamento Urbano": [
    "Contato com o cliente",
    "Envio de proposta comercial",
    "Envio de contrato",
    "Contrato assinado",
    "Marcar levantamento técnico",
    "Levantamento técnico",
    "Processamento de dados",
    "Elaboração de projeto técnico",
    "Elaboração de memorial descritivo",
    "Correção cruzada",
    "Emissão de ART",
    "Impressão de projeto",
    "Entrega ao cliente",
    "Coleta de NPS",
  ],
  "Georreferenciamento Rural": [
    "Contato com o cliente",
    "Envio de proposta comercial",
    "Envio de contrato",
    "Contrato assinado",
    "Marcar levantamento técnico",
    "Levantamento técnico",
    "Processamento de dados",
    "Elaboração de projeto técnico",
    "Elaboração de memorial descritivo",
    "Emissão de CAR",
    "Emissão certificação SIGEF",
    "Emissão de ITR",
    "Emissão de CCIR",
    "Correção cruzada",
    "Emissão de ART",
    "Impressão de projeto",
    "Entrega ao cliente",
    "Coleta de NPS",
  ],
  Aerofotogrametria: [
    "Contato com o cliente",
    "Envio de proposta comercial",
    "Envio de contrato",
    "Contrato assinado",
    "Marcar levantamento técnico",
    "Levantamento técnico aéreo",
    "Processamento das fotos",
    "Elaboração de projeto técnico",
    "Elaboração de memorial descritivo",
    "Correção cruzada",
    "Emissão de ART",
    "Impressão de projeto",
    "Entrega ao cliente",
    "Coleta de NPS",
  ],
  "Projeto de Loteamento": [
    "Contato com o cliente",
    "Envio de proposta comercial",
    "Envio de contrato",
    "Contrato assinado",
    "Marcar levantamento técnico",
    "Levantamento técnico",
    "Processamento de dados",
    "Elaboração de projeto técnico de loteamentos",
    "Elaboração de memorial descritivo",
    "Correção cruzada",
    "Emissão de ART",
    "Impressão de projeto",
    "Entrega ao cliente",
    "Coleta de NPS",
  ],
  "Execução de Loteamento": [
    "Contato com o cliente",
    "Envio de proposta comercial",
    "Envio de contrato",
    "Contrato assinado",
    "Marcar visita técnica",
    "Locação de piquetes",
    "Elaboração de memorial de campo",
    "Emissão de ART",
    "Coleta de NPS",
  ],
  "Execução de marcação de Lotes": [
    "Contato com o cliente",
    "Envio de proposta comercial",
    "Envio de contrato",
    "Contrato assinado",
    "Marcar visita técnica",
    "Locação de piquetes",
    "Elaboração de memorial de campo",
    "Emissão de ART",
    "Coleta de NPS",
  ],
  "Terraplenagem e nivelamento": [
    "Contato com o cliente",
    "Envio de proposta comercial",
    "Envio de contrato",
    "Contrato assinado",
    "Marcar levantamento técnico",
    "Levantamento técnico",
    "Processamento de dados",
    "Elaboração de projeto técnico",
    "Locação de piquetes",
    "Elaboração de memorial descritivo",
    "Correção cruzada",
    "Emissão de ART",
    "Impressão de projeto",
    "Entrega ao cliente",
    "Coleta de NPS",
  ],
  Estradas: [
    "Contato com o cliente",
    "Envio de proposta comercial",
    "Envio de contrato",
    "Contrato assinado",
    "Marcar levantamento técnico",
    "Levantamento técnico",
    "Processamento de dados",
    "Elaboração de projeto técnico",
    "Elaboração de memorial descritivo",
    "Correção cruzada",
    "Emissão de ART",
    "Impressão de projeto",
    "Entrega ao cliente",
    "Coleta de NPS",
  ],
  "Inspeção de radiância solar": [
    "Contato com o cliente",
    "Envio de proposta comercial",
    "Envio de contrato",
    "Contrato assinado",
    "Marcar levantamento técnico",
    "Levantamento técnico aéreo",
    "Processamento das fotos",
    "Elaboração de projeto técnico",
    "Elaboração de memorial descritivo",
    "Correção cruzada",
    "Emissão de ART",
    "Impressão de projeto",
    "Entrega ao cliente",
  ],
};
